name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Use example google-services.json
      run: cp app/google-services.example app/google-services.json

    - name: Create strings_other.xml
      run: |
        printf '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n    <string name="host_name">http://192.168.10.2:2283</string>\n    <string name="api_key">demo</string>\n    <string name="authentication_url">https://example.com</string>\n</resources>\n' > app/src/main/res/values/strings_other.xml

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
          name: immich-tv-debug.apk
          path: ./app/build/outputs/apk/debug/*.apk
